sources:
  - name: Symbol
    handler:
      openapi:
        source: https://raw.githubusercontent.com/symbol/symbol/refs/heads/new-docs/openapi/openapi-symbol.yml
        endpoint: https://your-node-url:3001
transforms:
  - rename:
      renames:
        - from:
            type: .*DTO$
          to:
            type: '{type}'
          useRegExpForTypes: true
serve:
  endpoint: /graphql
  playground: true
